global:
  scrape_interval: 15s

  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'api'
    scrape_interval: 5s
    metrics_path: "/metrics"
    static_configs:
      - targets: [ 'api:9095' ]