version: "3"
services:

  api:
    image: api
    ports:
      - "8080:8080"
      - "9095:9095"

  performance:
    image: performance-tests-api
    depends_on:
      - api

  prometheus:
    image: prom/prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - ./config/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./config/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./dashboards:/etc/grafana/dashboards
    ports:
      - "3000:3000"
    depends_on:
      - prometheus